Add missing __init__.py
This resolves the following error when running the tests:

    RuntimeError: Model class models.Participant doesn't declare an
    explicit app_label and isn't in an application in INSTALLED_APPS.